# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'caloriepic' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Firebase'
pod 'Firebase/Database'
pod 'Firebase/Analytics'


  # Pods for caloriepic

  target 'caloriepicTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'caloriepicUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
